FROM python:3.6 

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install requests
RUN pip3 install grpcio grpcio-tools hydra-core
RUN pip3 install pyyaml google-api-python-client protobuf
RUN pip3 install google-auth 
RUN pip3 install kubernetes 

#RUN git clone --recursive https://github.com/kubernetes-client/python.git
#WORKDIR python
#RUN python setup.py install 

ENV SOURCE_DIR spitfire/init

WORKDIR /
COPY $SOURCE_DIR/init.py ./
COPY infinite ./
