FROM python:3.6 

RUN pip install psycopg2
RUN pip install requests

RUN pip3 install grpcio grpcio-tools hydra-core
RUN pip3 install pyyaml google-api-python-client protobuf

RUN git clone --recursive https://github.com/kubernetes-client/python.git
WORKDIR python
RUN python setup.py install 

ENV SOURCE_DIR spitfire/init

WORKDIR /
COPY $SOURCE_DIR/init.py ./
COPY infinite ./
