FROM ubuntu:18.04
RUN apt-get update -y 
RUN apt-get upgrade -y
RUN apt-get install -y clang wget xxd build-essential python cmake python-pip pkg-config python-yaml libyaml-0-2 libyaml-dev systemd --fix-missing
RUN apt-get install -y git libtool autoconf pkg-config

ENV WORK_DIR /fuzzing
WORKDIR $WORK_DIR

# Get AFL
RUN wget http://lcamtuf.coredump.cx/afl/releases/afl-2.52b.tgz
RUN  tar xvf afl-2.52b.tgz
RUN rm afl-2.52b.tgz
WORKDIR $WORK_DIR/afl-2.52b
RUN make

# Get the target
WORKDIR /
RUN git clone https://gitlab.gnome.org/GNOME/libxml2.git
WORKDIR /libxml2
RUN git checkout 3e7e75bed2cf2853b0d42d635d36676b3330d475

# Move the target to /target_source
RUN cp -r /libxml2 /target_source

# Copy over to instrumented as well
WORKDIR $WORK_DIR
RUN cp -r /target_source ./instrumented

# Make regular
WORKDIR /target_source
RUN ./autogen.sh
RUN ./configure && make

# Make instrumented
WORKDIR $WORK_DIR/instrumented
RUN CFLAGS="-static -fno-PIE -fno-PIC" CC=$WORK_DIR/afl-2.52b/afl-clang ./autogen.sh
RUN CFLAGS="-static -fno-PIE -fno-PIC" CC=$WORK_DIR/afl-2.52b/afl-clang ./configure 
RUN CFLAGS="-static -fno-PIE -fno-PIC" CC=$WORK_DIR/afl-2.52b/afl-clang make

# Copy to instrumented 
WORKDIR /
RUN mv $WORK_DIR/instrumented/ /instrumented/

RUN mkdir /target /target-instr
RUN cp /target_source/.libs/xmllint /target
RUN cp -r /instrumented/xmllint /target-instr/xmllint

#RUN echo "$NAMESPACE"
#COPY infinite /
CMD mv target $NAMESPACE && mv target-instr $NAMESPACE

