FROM ubuntu:18.04
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y clang wget xxd build-essential python cmake python-pip pkg-config python-yaml libyaml-0-2 libyaml-dev systemd git libtool autoconf pkg-config --fix-missing

ENV WORK_DIR /fuzzing
WORKDIR $WORK_DIR

# Get AFL version 2.43b
RUN wget http://lcamtuf.coredump.cx/afl/releases/afl-2.43b.tgz
RUN  tar xvf afl-2.43b.tgz
RUN rm afl-2.43b.tgz
WORKDIR $WORK_DIR/afl-2.43b
RUN make

# Get binutils version 2.26
WORKDIR /
RUN wget http://ftp.gnu.org/gnu/binutils/binutils-2.26.tar.gz && tar -xf binutils-2.26.tar.gz
WORKDIR /binutils-2.26
# We need that warning ignored or it doesn't compile
RUN CFLAGS="-static -fno-PIE -fno-PIC -Wno-null-pointer-arithmetic -Wno-unused-command-line-argument" CC=$WORK_DIR/afl-2.43b/afl-clang ./configure 
RUN CFLAGS="-static -fno-PIE -fno-PIC -Wno-null-pointer-arithmetic -Wno-unused-command-line-argument" CC=$WORK_DIR/afl-2.43b/afl-clang make
WORKDIR binutils
RUN mkdir /target-instr 
RUN cp cxxfilt nm-new objdump strings size /target-instr

# Get FFMpeg version n0.5.10
WORKDIR /
RUN apt-get install nasm
RUN git clone https://github.com/FFmpeg/FFMpeg.git
WORKDIR /FFMpeg
RUN git checkout 9eaec5b8f010c805fd8e77216a1ec67eb20b1466 #version n0.5.10
RUN CFLAGS="-static -fno-PIE -fPIC -fheinous-gnu-extensions" CC=$WORK_DIR/afl-2.43b/afl-clang ./configure --cc=$WORK_DIR/afl-2.43b/afl-clang --extra-cflags="-fheinous-gnu-extensions" 
RUN CFLAGS="-static -fno-PIE -fPIC" CC=$WORK_DIR/afl-2.43b/afl-clang make 
RUN cp ffmpeg /target-instr/ffmpeg

# Get gif2png version 2.5.8
WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y upgrade && apt-get -y update && apt-get -y install libpng-dev xmlto curl 
RUN wget http://deb.debian.org/debian/pool/main/g/gif2png/gif2png_2.5.8.orig.tar.gz
RUN tar -xf gif2png_2.5.8.orig.tar.gz
WORKDIR /gif2png-2.5.8
RUN CFLAGS="-static -fno-PIE -fno-PIC" CC=$WORK_DIR/afl-2.43b/afl-clang ./configure 
RUN CFLAGS="-static -fno-PIE -fno-PIC" CC=$WORK_DIR/afl-2.43b/afl-clang make 
RUN cp gif2png /target-instr/gif2png

FROM alpine:latest
RUN mkdir /target /target-instr
COPY --from=0 /target-instr /target-instr
CMD mv target $NAMESPACE && mv target-instr $NAMESPACE


