defaults:
    - taint: panda
    - target: xmllint #tiff2rgba #xmllint
    - knowledge_base: pickle
    - coverage: panda 
    - fuzzer: gtfo
campaign:
  id: heather
  source_code_image: spitfire:v1 
  storage: 8Gi
images:
  init: "init:v1"
  knowledge_base: "knowledge-base:v1"
  fm: "fm:v1"
  seed_corpus: "seed-corpus:v1"
  target: "target:xmllint"
  code: "spitfire:v1"
  fuzzer: "fuzzer:v1"
  taint: "taint:v1"
  coverage: "coverage:v1" 
