defaults:
    - taint: panda
    - target: xmllint #tiff2rgba #xmllint
    - knowledge_base: pickle
    - coverage: panda 
    - fuzzer: gtfo
    - manager: spitfire
campaign:
  id: tim1
  source_code_image: spitfire:v1 
  storage: 4Gi
