FROM ubuntu
#CMD echo "hi" && ls /target && ls /gtfo-source && echo "seed" && ls /seed-corpus && echo "spittttfire: " && ls /spitfire && echo "coverage" && ls /coverage 
CMD echo "hi" && ls $TARGET_DIR && ls $GTFO_DIR && echo "seed" && ls $CORPUS_DIR && echo "spittttfire: " && ls $SPITFIRE && echo "coverage" && ls $COVERAGE_DIR
