FROM ubuntu
COPY init/seed-corpus/corpus /data/corpus

CMD cp /data/corpus/* /seed-corpus 
#CMD mkdir /shared/inputs/ && mkdir /shared/inputs/seed-corpus && cp /data/corpus/not_kitty.tiff /shared/inputs/seed-corpus
