#FROM pandare/panda:latest 
FROM spitfirepanda:python
WORKDIR /panda/panda/python/core
RUN python3.6 setup.py install

FROM raf:latest 
# Install qemu dependencies 
RUN apt-get update \
    && apt-get -y upgrade -o Dpkg::Options::="--force-confold" \
    && apt-get -y install ${image_extra_packages} \
        libcapstone3 libdwarf1 libprotobuf10 libprotobuf-c1 \
        python3.6 python3-pip vim libyaml-0-2 libyaml-dev genisoimage \
        $(apt-cache depends qemu-system-x86 | awk '/Depends:/{ print $2 }') \
    && apt-get -y install libcapstone3 libdwarf1 libprotobuf10 libprotobuf-c1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* /var/tmp/*

# Install more python dependencies
RUN pip3 install capstone 

# Take minimal set of panda files we need
RUN mkdir -p /usr/local/lib/python3.6/dist-packages/panda /panda/build/x86_64-softmmu /panda/pc-bios /panda/build/pc-bios 
COPY --from=0 /usr/local/lib/python3.6/dist-packages/panda /usr/local/lib/python3.6/dist-packages/panda
COPY --from=0 /panda/build/x86_64-softmmu /panda/build/x86_64-softmmu
COPY --from=0 /panda/build/pc-bios/ /panda/build/pc-bios
COPY --from=0 /panda/pc-bios /panda/pc-bios

WORKDIR /
ENV SOURCE_DIR spitfire/components/taint/panda
COPY ./infinite ./infinite
COPY $SOURCE_DIR/run.py ./
COPY $SOURCE_DIR/taint_analysis.py ./
