FROM ubuntu
COPY fuzzing-manager/seed-corpus/corpus /data/corpus
CMD cp /data/corpus/not_kitty.tiff /seed-corpus
#mkdir /shared/inputs/ && mkdir /shared/inputs/seed-corpus && cp /data/corpus/not_kitty.tiff /shared/inputs/seed-corpus
#${CORPUS_DIR}
#/seed-corpus
