# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taint_analysis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='taint_analysis.proto',
  package='taint_analysis',
  serialized_pb=_b('\n\x14taint_analysis.proto\x12\x0etaint_analysis\"@\n\x14TaintAnalysisSummary\x12\x14\n\x0cprogram_hash\x18\x01 \x02(\t\x12\x12\n\ninput_hash\x18\x02 \x02(\t\"/\n\x0f\x46uzzableByteSet\x12\r\n\x05index\x18\x01 \x02(\r\x12\r\n\x05label\x18\x02 \x03(\r\"M\n\x12TaintedInstruction\x12\r\n\x05index\x18\x01 \x02(\r\x12\n\n\x02pc\x18\x02 \x02(\x04\x12\x0e\n\x06module\x18\x03 \x02(\t\x12\x0c\n\x04type\x18\x04 \x02(\t\"\xbc\x01\n\x0cTaintMapping\x12\x19\n\x11\x66uzzable_byte_set\x18\x01 \x02(\r\x12\x1b\n\x13tainted_instruction\x18\x02 \x02(\r\x12\r\n\x05value\x18\x03 \x02(\x04\x12\x14\n\x0cvalue_length\x18\x04 \x02(\r\x12\x13\n\x0btrace_point\x18\x05 \x02(\x02\x12\x1c\n\x14min_compute_distance\x18\x06 \x02(\r\x12\x1c\n\x14max_compute_distance\x18\x07 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TAINTANALYSISSUMMARY = _descriptor.Descriptor(
  name='TaintAnalysisSummary',
  full_name='taint_analysis.TaintAnalysisSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='program_hash', full_name='taint_analysis.TaintAnalysisSummary.program_hash', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_hash', full_name='taint_analysis.TaintAnalysisSummary.input_hash', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=104,
)


_FUZZABLEBYTESET = _descriptor.Descriptor(
  name='FuzzableByteSet',
  full_name='taint_analysis.FuzzableByteSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='taint_analysis.FuzzableByteSet.index', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='taint_analysis.FuzzableByteSet.label', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=153,
)


_TAINTEDINSTRUCTION = _descriptor.Descriptor(
  name='TaintedInstruction',
  full_name='taint_analysis.TaintedInstruction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='taint_analysis.TaintedInstruction.index', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pc', full_name='taint_analysis.TaintedInstruction.pc', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module', full_name='taint_analysis.TaintedInstruction.module', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='taint_analysis.TaintedInstruction.type', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=232,
)


_TAINTMAPPING = _descriptor.Descriptor(
  name='TaintMapping',
  full_name='taint_analysis.TaintMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fuzzable_byte_set', full_name='taint_analysis.TaintMapping.fuzzable_byte_set', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tainted_instruction', full_name='taint_analysis.TaintMapping.tainted_instruction', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='taint_analysis.TaintMapping.value', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_length', full_name='taint_analysis.TaintMapping.value_length', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trace_point', full_name='taint_analysis.TaintMapping.trace_point', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_compute_distance', full_name='taint_analysis.TaintMapping.min_compute_distance', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_compute_distance', full_name='taint_analysis.TaintMapping.max_compute_distance', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=423,
)

DESCRIPTOR.message_types_by_name['TaintAnalysisSummary'] = _TAINTANALYSISSUMMARY
DESCRIPTOR.message_types_by_name['FuzzableByteSet'] = _FUZZABLEBYTESET
DESCRIPTOR.message_types_by_name['TaintedInstruction'] = _TAINTEDINSTRUCTION
DESCRIPTOR.message_types_by_name['TaintMapping'] = _TAINTMAPPING

TaintAnalysisSummary = _reflection.GeneratedProtocolMessageType('TaintAnalysisSummary', (_message.Message,), dict(
  DESCRIPTOR = _TAINTANALYSISSUMMARY,
  __module__ = 'taint_analysis_pb2'
  # @@protoc_insertion_point(class_scope:taint_analysis.TaintAnalysisSummary)
  ))
_sym_db.RegisterMessage(TaintAnalysisSummary)

FuzzableByteSet = _reflection.GeneratedProtocolMessageType('FuzzableByteSet', (_message.Message,), dict(
  DESCRIPTOR = _FUZZABLEBYTESET,
  __module__ = 'taint_analysis_pb2'
  # @@protoc_insertion_point(class_scope:taint_analysis.FuzzableByteSet)
  ))
_sym_db.RegisterMessage(FuzzableByteSet)

TaintedInstruction = _reflection.GeneratedProtocolMessageType('TaintedInstruction', (_message.Message,), dict(
  DESCRIPTOR = _TAINTEDINSTRUCTION,
  __module__ = 'taint_analysis_pb2'
  # @@protoc_insertion_point(class_scope:taint_analysis.TaintedInstruction)
  ))
_sym_db.RegisterMessage(TaintedInstruction)

TaintMapping = _reflection.GeneratedProtocolMessageType('TaintMapping', (_message.Message,), dict(
  DESCRIPTOR = _TAINTMAPPING,
  __module__ = 'taint_analysis_pb2'
  # @@protoc_insertion_point(class_scope:taint_analysis.TaintMapping)
  ))
_sym_db.RegisterMessage(TaintMapping)


# @@protoc_insertion_point(module_scope)
