
#
# This is the yaml file for panda 
# So, all config necessary to run panda taint analysis
#

panda_clone_string: "git clone -b spitfire_0 https://github.com/panda-re/panda.git"

panda_container_name: "panda_spitfire"

panda_container_transfer_dir: "/home/tleek/transfer"