FROM ubuntu
CMD echo "Target Regular:" && ls /target && echo "Seed Corpus:" && ls /seed-corpus && echo "Spitfire: " && ls /spitfire 
#CMD echo "hi" && ls $SHARED_DIR && echo "AFTER" && $TARGET_DIR && ls $GTFO_DIR && echo "seed" && ls $CORPUS_DIR && echo "spittttfire: " && ls $SPITFIRE && echo "coverage" && ls $COVERAGE_DIR
